version: '2'
services:
  opportunities-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/Opportunities/postgresql/:/var/lib/postgresql/data/
    environment:
      # - POSTGRES_USER=Opportunities
      - POSTGRES_USER=sandbox
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
